[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"
buildContext = "."

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100 